Redirected errors to STDOUT.

diff --git a/library_functions b/library_functions
--- a/library_functions
+++ b/library_functions
@@ -91,7 +91,7 @@ EOF
 # Check if user is running as root.
 function root_check {
   if [ $(id -u) -ne 0 ]; then
-    echo "This script must be run as root."
+    echo "This script must be run as root." >&2
     exit 126
   fi
 }
@@ -103,7 +103,7 @@ function is_command {
   for program in $@; do
     hash ${program} > /dev/null 2>&1
     if [ $? != 0 ]; then
-      echo "Command not found: ${program}"
+      echo "Command not found: ${program}" >&2
       FAILURE='true'
     fi
   done
